Window.SetBackgroundTopColor(0.043, 0.067, 0.094);
Window.SetBackgroundBottomColor(0.051, 0.153, 0.259);
logo.image = Image("symbol.png");
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
logo.sprite.SetY(Window.GetHeight() / 2 - logo.image.GetHeight() / 2 - 30);
dot.image = Image("dot.png");
dot.sprite = Sprite(dot.image);
dot.idle_image = Image("dot-white.png");
dot.idle0 = Sprite(dot.idle_image);
dot.idle1 = Sprite(dot.idle_image);
dot.idle2 = Sprite(dot.idle_image);
dot.idle3 = Sprite(dot.idle_image);
dot.idle4 = Sprite(dot.idle_image);
dot.y = Window.GetHeight() / 2 + 105;
dot.idle0.SetPosition(Window.GetWidth() / 2 - 62, dot.y, 5);
dot.idle1.SetPosition(Window.GetWidth() / 2 - 31, dot.y, 5);
dot.idle2.SetPosition(Window.GetWidth() / 2, dot.y, 5);
dot.idle3.SetPosition(Window.GetWidth() / 2 + 31, dot.y, 5);
dot.idle4.SetPosition(Window.GetWidth() / 2 + 62, dot.y, 5);
fun refresh_callback () {
  dot.sprite.SetX(Window.GetWidth() / 2 - 62 + (Math.Int(Time() * 2.5) % 5) * 31);
  dot.sprite.SetY(dot.y);
  dot.sprite.SetZ(10);
}
Plymouth.SetRefreshFunction(refresh_callback);
