Window.SetBackgroundTopColor(0.043, 0.067, 0.094);
Window.SetBackgroundBottomColor(0.051, 0.153, 0.259);
logo.image = Image("symbol.png");
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
logo.sprite.SetY(Window.GetHeight() / 2 - logo.image.GetHeight() / 2 - 30);
dot.image = Image("dot.png");
dot.sprite = Sprite(dot.image);
fun refresh_callback () {
  dot.sprite.SetX(Window.GetWidth() / 2 - 42 + (Math.Int(Time() * 2) % 4) * 28);
  dot.sprite.SetY(Window.GetHeight() / 2 + 105);
}
Plymouth.SetRefreshFunction(refresh_callback);
